script: rake ci

cache: bundler

language: ruby

rvm:
  - rbx
  - jruby
  - 2.2.2
  - ruby-head
  - jruby-head

matrix:

  fast_finish: true

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: CELLULOID_BACKPORTED=true
    - env: CELLULOID_BACKPORTED=false CELLULOID_LEAKTEST=true
    - env: CELLULOID_BACKPORTED=false CELLULOID_TASK_CLASS=Threaded
    - env: CELLULOID_BACKPORTED=true CELLULOID_TASK_CLASS=Threaded

env:
  global:
    - NUMBER_OF_PROCESSORS=4 CELLULOID_CONFIG_FILE=.env-ci
  matrix:
    - CELLULOID_BACKPORTED=true
    - CELLULOID_BACKPORTED=false
    - CELLULOID_BACKPORTED=false CELLULOID_LEAKTEST=true
    - CELLULOID_BACKPORTED=false CELLULOID_TASK_CLASS=Threaded
    - CELLULOID_BACKPORTED=true CELLULOID_TASK_CLASS=Threaded

notifications:
  irc: "irc.freenode.org#celluloid"

#de Removing soon: https://github.com/bundler/bundler/issues/3269#issuecomment-65842225
#de before_install:
#de   # Only use 1 job until Travis fixes the rbx --jobs issue.
#de   - if [ "$TRAVIS_RUBY_VERSION" == "rbx" ] ; then export BUNDLE_JOBS=1 ; else export BUNDLE_JOBS=4; fi

sudo: false
install: bundle install --without=development
